# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minds/qa/cangen.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minds/qa/cangen.proto',
  package='minds.qa',
  syntax='proto3',
  serialized_pb=_b('\n\x15minds/qa/cangen.proto\x12\x08minds.qa\".\n\x1eUnstructuredCandidateInputText\x12\x0c\n\x04text\x18\x01 \x01(\t\"5\n#UnstructuredCandidateResultDocument\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')
)




_UNSTRUCTUREDCANDIDATEINPUTTEXT = _descriptor.Descriptor(
  name='UnstructuredCandidateInputText',
  full_name='minds.qa.UnstructuredCandidateInputText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='minds.qa.UnstructuredCandidateInputText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=81,
)


_UNSTRUCTUREDCANDIDATERESULTDOCUMENT = _descriptor.Descriptor(
  name='UnstructuredCandidateResultDocument',
  full_name='minds.qa.UnstructuredCandidateResultDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='minds.qa.UnstructuredCandidateResultDocument.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['UnstructuredCandidateInputText'] = _UNSTRUCTUREDCANDIDATEINPUTTEXT
DESCRIPTOR.message_types_by_name['UnstructuredCandidateResultDocument'] = _UNSTRUCTUREDCANDIDATERESULTDOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UnstructuredCandidateInputText = _reflection.GeneratedProtocolMessageType('UnstructuredCandidateInputText', (_message.Message,), dict(
  DESCRIPTOR = _UNSTRUCTUREDCANDIDATEINPUTTEXT,
  __module__ = 'minds.qa.cangen_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.UnstructuredCandidateInputText)
  ))
_sym_db.RegisterMessage(UnstructuredCandidateInputText)

UnstructuredCandidateResultDocument = _reflection.GeneratedProtocolMessageType('UnstructuredCandidateResultDocument', (_message.Message,), dict(
  DESCRIPTOR = _UNSTRUCTUREDCANDIDATERESULTDOCUMENT,
  __module__ = 'minds.qa.cangen_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.UnstructuredCandidateResultDocument)
  ))
_sym_db.RegisterMessage(UnstructuredCandidateResultDocument)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
