# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from minds.qa import question_analysis_pb2 as minds_dot_qa_dot_question__analysis__pb2


class QuestionAnalysisServiceStub(object):
  """
  message QuizMetaData {
  string question_origin = 1;
  string question_round = 2;
  int32 ui_num = 3;
  string question_form = 4;
  string question_cat = 5;
  repeated string question_options = 6;
  repeated string question_comp_opts = 7;
  repeated string comp_answer_candidates = 8;
  repeated string question_hints = 9;
  }

  message OriginalQuestionInformation {
  OriginalQuestionUnit org_q_unit = 1;
  OriginalSentenceFrame org_s_frame = 2;
  int32 q_decomp_type = 3;
  string str_q_decomp_type = 4;
  repeated vSubQRelation v_sub_q_relation = 5;
  repeated vSubQInfo v_sub_q_info = 6;
  double d_qh_weight = 7;
  }

  message OriginalQuestionUnit {
  string str_question = 1;
  string tagged_question = 2;
  LanguageAnalysisDocument language_document = 3;
  repeated vQT v_qts = 4;
  repeated vQF v_qfs = 5;
  repeated vLAT v_lats = 6;
  repeated vSAT v_sats = 7;
  repeated vSARoot v_sa_roots = 8;
  repeated vTitle v_titles = 9;
  repeated vQTopic v_q_topics = 10;
  repeated vQuotation v_quotations = 11;
  CompTargetInfo comp_target_info = 12;
  repeated AnswerConstraint answer_constraints = 13;
  }

  message LanguageAnalysisDocument {
  string doc_id = 1;
  string dct = 2;
  string category = 3;
  double category_weight = 4;
  MetaInformation meta_info = 5;
  Sentence sentences = 6;
  Entity entities = 7;
  }

  message MetaInformation {

  }

  message Sentence {
  int32 seq = 1;
  string reserve_str = 2;
  string text = 3;
  repeated Word words = 4;
  repeated Morpheme morps = 5;
  repeated MorphemeEval morph_evals = 6;
  repeated NamedEntity nes = 7;
  repeated WordSenseDisambiguation wsds = 8;
  repeated Chunk chunks = 9;
  repeated DependencyParser dependency_parsers = 10;
  repeated PhraseClause phrase_clauses = 11;
  repeated SRL srls = 12;
  repeated SRLInformationExtraction srl_infos = 13;
  repeated Relation relations = 14;
  repeated ZeroAnaphora zas = 15;
  }

  message Word {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  int32 begin = 4;
  int32 end = 5;
  }

  message Morpheme {
  int32 seq = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  int32 weight = 5;
  }

  message MorphemeEval {
  int32 seq = 1;
  string target = 2;
  string result = 3;
  int32 word_id = 4;
  int32 m_begin = 5;
  int32 m_end = 6;
  }

  message NamedEntity {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  int32 begin = 4;
  int32 end = 5;
  double weight = 6;
  int32 common_noun = 7;
  }

  message WordSenseDisambiguation {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  string scode = 4;
  double weight = 5;
  int32 position = 6;
  int32 begin = 7;
  int32 end = 8;
  }

  message Chunk {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  int32 begin = 4;
  int32 end = 5;
  double weight = 6;
  }

  message DependencyParser {
  int32 seq = 1;
  string text = 2;
  int32 head = 3;
  string label = 4;
  repeated int32 mods = 5;
  double weight = 6;
  }

  message PhraseElement {
  string text = 1;
  string label = 2;
  int32 begin = 3;
  int32 end = 4;
  string ne_type = 5;
  }

  message PhraseClause {
  int32 seq = 1;
  string label = 2;
  string text = 3;
  int32 begin = 4;
  int32 end = 5;
  int32 key_begin = 6;
  int32 head_phrase = 7;
  repeated int32 sub_phrases = 8;
  double weight = 9;
  repeated PhraseElement elements = 10;
  }

  message SRLArgument {
  string type = 1;
  int32 word_id = 2;
  string text = 3;
  }

  message SRL {
  string verb = 1;
  int32 sense = 2;
  int32 word_id = 3;
  double weight = 4;
  repeated SRLArgument arguments = 5;
  }

  message SRLInformationExtraction {
  string pred = 1;
  int32 sense = 2;
  int32 word_id = 3;
  double weight = 4;
  repeated SRLArgument arguments = 5;
  }

  message RelationProperty {
  string type = 1;
  string value = 2;
  string value_type = 3;
  int32 begin = 4;
  int32 end = 5;
  }

  message Relation {
  string type = 1;
  string trigger = 2;
  string sub = 3;
  string sub_type = 4;
  int32 begin = 5;
  int32 end = 6;
  double weight = 7;
  repeated RelationProperty rel_props = 8;
  }

  message ZeroAnaphora {
  int32 seq = 1;
  int32 verb_wid = 2;
  int32 ant_sid = 3;
  int32 ant_wid = 4;
  string type = 5;
  int32 istitle = 6;
  double weight = 7;
  }

  message Entity {

  }

  message vQT {
  int32 qt = 1;
  string strQTClue = 2;
  int32 uiSentID = 3;
  normQTCLue norm_qt_clue = 4;
  }

  message normQTClue {
  int32 seq = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  }

  message vQF {

  }

  message vLAT {
  string strLAT = 1;
  repeated vCompoundLAT v_compound_lats = 2;
  int32 uiSentID = 3;
  string strID = 4;
  double dWeightLAT = 5;
  double dConfidenceLAT = 6;
  repeated vLATMorp v_lat_morps = 7;
  repeated VRuleID v_rule_ids = 8;
  }

  message vCompoundLAT {

  }

  message vLATMorp {
  int32 seq = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  }

  message vRuleID {

  }

  message vSAT {
  int32 atSAT = 1;
  string strSAT = 2;
  repeated ExpanseSAT expanse_sats = 3;
  double dWeightSAT = 4;
  double dConfidenceSAT = 5;
  repeated VRuleID v_rule_ids = 6;
  }

  message ExpanseSAT {

  }

  message vSARoots {
  int32 atSAT = 1;
  string strSAT = 2;
  repeated ExpanseSAT expanse_sats = 3;
  double dWeightSAT = 4;
  double dConfidenceSAT = 5;
  repeated VRuleID v_rule_ids = 6;
  }

  message vTitile {
  string strEntity = 1;
  int32 uiSentID = 2;
  int32 atEntityType = 3;
  string strEntityType = 4;
  double dWeightTitle = 5;
  repeated EntityMorp entity_morps = 6;
  repeated EntityInfo entity_infos = 7;
  }

  message EntityMorp {
  int32 id = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  }

  message EntityInfo {
  string strNormEntity = 1;
  string strId = 2;
  string strExplain = 3;
  double dWeightEn = 4;
  }

  message vQTopic {

  }

  message vQuotation {

  }

  message CompTargetInfo {
  string strTarget = 1;
  }

  message AnswerConstraint {

  }

  message OriginalSentenceFrame {
  Qif qif = 1;
  FactoidQ fact_id_q = 2;
  }

  message Qif {
  string p_type = 1;
  string q_type = 2;
  string q_structure = 3;
  string q_semantic = 4;
  string q_domain = 5;
  string q_id = 6;
  string sqid = 7;
  string question = 8;
  repeated SatList sat_lists = 9;
  repeated LatList lat_lists = 10;
  string negation = 11;
  repeated SubQSemFrameList sub_q_sem_frame_lists = 12;
  repeated ArgFrameList arg_frame_lists = 13;
  }

  message FactoidQ {
  int32 q_type = 1;
  repeated vNormal v_normals = 2;
  repeated vGuinness v_guinesses = 3;
  }

  message SatList {
  }

  message LatList {
  }

  message SubQSemFrameList {
  }

  message ArgFrameList {
  }

  message vNormal {
  }

  message vGuinness {
  }

  message vSubQRelation {
  }

  message vSubQInfo {
  }

  message vQHypo {
  }

  message QuestionClassification {
  repeated vQDomain v_q_domains = 1;
  repeated AnsQType ans_q_type = 2;
  repeated vSynQType v_syn_q_type = 3;
  repeated vSemQType v_sem_q_type = 4;
  }

  message vQDomain {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;

  }

  message AnsQType {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;
  }

  message vSynQType {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;
  }

  message vSemQType {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;
  }

  message AnalyzeResult {
  int32 gen_qif = 1;
  QuizMetaData quiz_meta_data = 2;
  OriginalQuestionInformation original_question_info = 3;
  repeated vQHypo v_q_hypos = 4;
  QuestionClassification question_classification = 5;
  }
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProvider = channel.unary_unary(
        '/minds.qa.QuestionAnalysisService/GetProvider',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=minds_dot_qa_dot_question__analysis__pb2.Provider.FromString,
        )
    self.QuestionAnalyze = channel.unary_unary(
        '/minds.qa.QuestionAnalysisService/QuestionAnalyze',
        request_serializer=minds_dot_qa_dot_question__analysis__pb2.QuestionInputText.SerializeToString,
        response_deserializer=minds_dot_qa_dot_question__analysis__pb2.QuestionAnalysisResultDocument.FromString,
        )


class QuestionAnalysisServiceServicer(object):
  """
  message QuizMetaData {
  string question_origin = 1;
  string question_round = 2;
  int32 ui_num = 3;
  string question_form = 4;
  string question_cat = 5;
  repeated string question_options = 6;
  repeated string question_comp_opts = 7;
  repeated string comp_answer_candidates = 8;
  repeated string question_hints = 9;
  }

  message OriginalQuestionInformation {
  OriginalQuestionUnit org_q_unit = 1;
  OriginalSentenceFrame org_s_frame = 2;
  int32 q_decomp_type = 3;
  string str_q_decomp_type = 4;
  repeated vSubQRelation v_sub_q_relation = 5;
  repeated vSubQInfo v_sub_q_info = 6;
  double d_qh_weight = 7;
  }

  message OriginalQuestionUnit {
  string str_question = 1;
  string tagged_question = 2;
  LanguageAnalysisDocument language_document = 3;
  repeated vQT v_qts = 4;
  repeated vQF v_qfs = 5;
  repeated vLAT v_lats = 6;
  repeated vSAT v_sats = 7;
  repeated vSARoot v_sa_roots = 8;
  repeated vTitle v_titles = 9;
  repeated vQTopic v_q_topics = 10;
  repeated vQuotation v_quotations = 11;
  CompTargetInfo comp_target_info = 12;
  repeated AnswerConstraint answer_constraints = 13;
  }

  message LanguageAnalysisDocument {
  string doc_id = 1;
  string dct = 2;
  string category = 3;
  double category_weight = 4;
  MetaInformation meta_info = 5;
  Sentence sentences = 6;
  Entity entities = 7;
  }

  message MetaInformation {

  }

  message Sentence {
  int32 seq = 1;
  string reserve_str = 2;
  string text = 3;
  repeated Word words = 4;
  repeated Morpheme morps = 5;
  repeated MorphemeEval morph_evals = 6;
  repeated NamedEntity nes = 7;
  repeated WordSenseDisambiguation wsds = 8;
  repeated Chunk chunks = 9;
  repeated DependencyParser dependency_parsers = 10;
  repeated PhraseClause phrase_clauses = 11;
  repeated SRL srls = 12;
  repeated SRLInformationExtraction srl_infos = 13;
  repeated Relation relations = 14;
  repeated ZeroAnaphora zas = 15;
  }

  message Word {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  int32 begin = 4;
  int32 end = 5;
  }

  message Morpheme {
  int32 seq = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  int32 weight = 5;
  }

  message MorphemeEval {
  int32 seq = 1;
  string target = 2;
  string result = 3;
  int32 word_id = 4;
  int32 m_begin = 5;
  int32 m_end = 6;
  }

  message NamedEntity {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  int32 begin = 4;
  int32 end = 5;
  double weight = 6;
  int32 common_noun = 7;
  }

  message WordSenseDisambiguation {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  string scode = 4;
  double weight = 5;
  int32 position = 6;
  int32 begin = 7;
  int32 end = 8;
  }

  message Chunk {
  int32 seq = 1;
  string text = 2;
  string type = 3;
  int32 begin = 4;
  int32 end = 5;
  double weight = 6;
  }

  message DependencyParser {
  int32 seq = 1;
  string text = 2;
  int32 head = 3;
  string label = 4;
  repeated int32 mods = 5;
  double weight = 6;
  }

  message PhraseElement {
  string text = 1;
  string label = 2;
  int32 begin = 3;
  int32 end = 4;
  string ne_type = 5;
  }

  message PhraseClause {
  int32 seq = 1;
  string label = 2;
  string text = 3;
  int32 begin = 4;
  int32 end = 5;
  int32 key_begin = 6;
  int32 head_phrase = 7;
  repeated int32 sub_phrases = 8;
  double weight = 9;
  repeated PhraseElement elements = 10;
  }

  message SRLArgument {
  string type = 1;
  int32 word_id = 2;
  string text = 3;
  }

  message SRL {
  string verb = 1;
  int32 sense = 2;
  int32 word_id = 3;
  double weight = 4;
  repeated SRLArgument arguments = 5;
  }

  message SRLInformationExtraction {
  string pred = 1;
  int32 sense = 2;
  int32 word_id = 3;
  double weight = 4;
  repeated SRLArgument arguments = 5;
  }

  message RelationProperty {
  string type = 1;
  string value = 2;
  string value_type = 3;
  int32 begin = 4;
  int32 end = 5;
  }

  message Relation {
  string type = 1;
  string trigger = 2;
  string sub = 3;
  string sub_type = 4;
  int32 begin = 5;
  int32 end = 6;
  double weight = 7;
  repeated RelationProperty rel_props = 8;
  }

  message ZeroAnaphora {
  int32 seq = 1;
  int32 verb_wid = 2;
  int32 ant_sid = 3;
  int32 ant_wid = 4;
  string type = 5;
  int32 istitle = 6;
  double weight = 7;
  }

  message Entity {

  }

  message vQT {
  int32 qt = 1;
  string strQTClue = 2;
  int32 uiSentID = 3;
  normQTCLue norm_qt_clue = 4;
  }

  message normQTClue {
  int32 seq = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  }

  message vQF {

  }

  message vLAT {
  string strLAT = 1;
  repeated vCompoundLAT v_compound_lats = 2;
  int32 uiSentID = 3;
  string strID = 4;
  double dWeightLAT = 5;
  double dConfidenceLAT = 6;
  repeated vLATMorp v_lat_morps = 7;
  repeated VRuleID v_rule_ids = 8;
  }

  message vCompoundLAT {

  }

  message vLATMorp {
  int32 seq = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  }

  message vRuleID {

  }

  message vSAT {
  int32 atSAT = 1;
  string strSAT = 2;
  repeated ExpanseSAT expanse_sats = 3;
  double dWeightSAT = 4;
  double dConfidenceSAT = 5;
  repeated VRuleID v_rule_ids = 6;
  }

  message ExpanseSAT {

  }

  message vSARoots {
  int32 atSAT = 1;
  string strSAT = 2;
  repeated ExpanseSAT expanse_sats = 3;
  double dWeightSAT = 4;
  double dConfidenceSAT = 5;
  repeated VRuleID v_rule_ids = 6;
  }

  message vTitile {
  string strEntity = 1;
  int32 uiSentID = 2;
  int32 atEntityType = 3;
  string strEntityType = 4;
  double dWeightTitle = 5;
  repeated EntityMorp entity_morps = 6;
  repeated EntityInfo entity_infos = 7;
  }

  message EntityMorp {
  int32 id = 1;
  string lemma = 2;
  string type = 3;
  int32 position = 4;
  }

  message EntityInfo {
  string strNormEntity = 1;
  string strId = 2;
  string strExplain = 3;
  double dWeightEn = 4;
  }

  message vQTopic {

  }

  message vQuotation {

  }

  message CompTargetInfo {
  string strTarget = 1;
  }

  message AnswerConstraint {

  }

  message OriginalSentenceFrame {
  Qif qif = 1;
  FactoidQ fact_id_q = 2;
  }

  message Qif {
  string p_type = 1;
  string q_type = 2;
  string q_structure = 3;
  string q_semantic = 4;
  string q_domain = 5;
  string q_id = 6;
  string sqid = 7;
  string question = 8;
  repeated SatList sat_lists = 9;
  repeated LatList lat_lists = 10;
  string negation = 11;
  repeated SubQSemFrameList sub_q_sem_frame_lists = 12;
  repeated ArgFrameList arg_frame_lists = 13;
  }

  message FactoidQ {
  int32 q_type = 1;
  repeated vNormal v_normals = 2;
  repeated vGuinness v_guinesses = 3;
  }

  message SatList {
  }

  message LatList {
  }

  message SubQSemFrameList {
  }

  message ArgFrameList {
  }

  message vNormal {
  }

  message vGuinness {
  }

  message vSubQRelation {
  }

  message vSubQInfo {
  }

  message vQHypo {
  }

  message QuestionClassification {
  repeated vQDomain v_q_domains = 1;
  repeated AnsQType ans_q_type = 2;
  repeated vSynQType v_syn_q_type = 3;
  repeated vSemQType v_sem_q_type = 4;
  }

  message vQDomain {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;

  }

  message AnsQType {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;
  }

  message vSynQType {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;
  }

  message vSemQType {
  int32 q_type_4_chg = 1;
  string str_q_type_4_chg = 2;
  double d_weight_cqt = 3;
  repeated vRuleId v_rule_ids = 4;
  }

  message AnalyzeResult {
  int32 gen_qif = 1;
  QuizMetaData quiz_meta_data = 2;
  OriginalQuestionInformation original_question_info = 3;
  repeated vQHypo v_q_hypos = 4;
  QuestionClassification question_classification = 5;
  }
  """

  def GetProvider(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def QuestionAnalyze(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_QuestionAnalysisServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProvider': grpc.unary_unary_rpc_method_handler(
          servicer.GetProvider,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=minds_dot_qa_dot_question__analysis__pb2.Provider.SerializeToString,
      ),
      'QuestionAnalyze': grpc.unary_unary_rpc_method_handler(
          servicer.QuestionAnalyze,
          request_deserializer=minds_dot_qa_dot_question__analysis__pb2.QuestionInputText.FromString,
          response_serializer=minds_dot_qa_dot_question__analysis__pb2.QuestionAnalysisResultDocument.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'minds.qa.QuestionAnalysisService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
