# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HNet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HNet.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nHNet.proto\"@\n\x07HNetDoc\x12\x18\n\x10\x63ontext_original\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x01(\t\x12\n\n\x02\x64p\x18\x03 \x01(\t\"e\n\tHNetInput\x12\x19\n\x11question_original\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x13\n\x0bquestion_dp\x18\x03 \x01(\t\x12\x16\n\x04\x64ocs\x18\x04 \x03(\x0b\x32\x08.HNetDoc\"*\n\nHNetOutput\x12\x0e\n\x06\x61nswer\x18\x01 \x03(\x05\x12\x0c\n\x04prob\x18\x02 \x01(\x02\"+\n\x0bHNetOutputs\x12\x1c\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x0b.HNetOutput2-\n\x04HNet\x12%\n\x07Predict\x12\n.HNetInput\x1a\x0c.HNetOutputs\"\x00\x62\x06proto3')
)




_HNETDOC = _descriptor.Descriptor(
  name='HNetDoc',
  full_name='HNetDoc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='context_original', full_name='HNetDoc.context_original', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='context', full_name='HNetDoc.context', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dp', full_name='HNetDoc.dp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=78,
)


_HNETINPUT = _descriptor.Descriptor(
  name='HNetInput',
  full_name='HNetInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question_original', full_name='HNetInput.question_original', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='question', full_name='HNetInput.question', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='question_dp', full_name='HNetInput.question_dp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docs', full_name='HNetInput.docs', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=181,
)


_HNETOUTPUT = _descriptor.Descriptor(
  name='HNetOutput',
  full_name='HNetOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='HNetOutput.answer', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='HNetOutput.prob', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=225,
)


_HNETOUTPUTS = _descriptor.Descriptor(
  name='HNetOutputs',
  full_name='HNetOutputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answers', full_name='HNetOutputs.answers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=270,
)

_HNETINPUT.fields_by_name['docs'].message_type = _HNETDOC
_HNETOUTPUTS.fields_by_name['answers'].message_type = _HNETOUTPUT
DESCRIPTOR.message_types_by_name['HNetDoc'] = _HNETDOC
DESCRIPTOR.message_types_by_name['HNetInput'] = _HNETINPUT
DESCRIPTOR.message_types_by_name['HNetOutput'] = _HNETOUTPUT
DESCRIPTOR.message_types_by_name['HNetOutputs'] = _HNETOUTPUTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HNetDoc = _reflection.GeneratedProtocolMessageType('HNetDoc', (_message.Message,), dict(
  DESCRIPTOR = _HNETDOC,
  __module__ = 'HNet_pb2'
  # @@protoc_insertion_point(class_scope:HNetDoc)
  ))
_sym_db.RegisterMessage(HNetDoc)

HNetInput = _reflection.GeneratedProtocolMessageType('HNetInput', (_message.Message,), dict(
  DESCRIPTOR = _HNETINPUT,
  __module__ = 'HNet_pb2'
  # @@protoc_insertion_point(class_scope:HNetInput)
  ))
_sym_db.RegisterMessage(HNetInput)

HNetOutput = _reflection.GeneratedProtocolMessageType('HNetOutput', (_message.Message,), dict(
  DESCRIPTOR = _HNETOUTPUT,
  __module__ = 'HNet_pb2'
  # @@protoc_insertion_point(class_scope:HNetOutput)
  ))
_sym_db.RegisterMessage(HNetOutput)

HNetOutputs = _reflection.GeneratedProtocolMessageType('HNetOutputs', (_message.Message,), dict(
  DESCRIPTOR = _HNETOUTPUTS,
  __module__ = 'HNet_pb2'
  # @@protoc_insertion_point(class_scope:HNetOutputs)
  ))
_sym_db.RegisterMessage(HNetOutputs)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class HNetStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Predict = channel.unary_unary(
          '/HNet/Predict',
          request_serializer=HNetInput.SerializeToString,
          response_deserializer=HNetOutputs.FromString,
          )


  class HNetServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def Predict(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_HNetServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Predict': grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=HNetInput.FromString,
            response_serializer=HNetOutputs.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'HNet', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaHNetServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Predict(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaHNetStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def Predict(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Predict.future = None


  def beta_create_HNet_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('HNet', 'Predict'): HNetInput.FromString,
    }
    response_serializers = {
      ('HNet', 'Predict'): HNetOutputs.SerializeToString,
    }
    method_implementations = {
      ('HNet', 'Predict'): face_utilities.unary_unary_inline(servicer.Predict),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_HNet_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('HNet', 'Predict'): HNetInput.SerializeToString,
    }
    response_deserializers = {
      ('HNet', 'Predict'): HNetOutputs.FromString,
    }
    cardinalities = {
      'Predict': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'HNet', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
