# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minds_mrc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minds_mrc.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0fminds_mrc.proto\";\n\nMrcPassage\x12\x10\n\x08original\x18\x01 \x01(\t\x12\x0c\n\x04morp\x18\x02 \x01(\t\x12\r\n\x05words\x18\x03 \x03(\t\";\n\x08MrcInput\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x1d\n\x08passages\x18\x02 \x03(\x0b\x32\x0b.MrcPassage\")\n\tMrcOutput\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0c\n\x04prob\x18\x02 \x01(\x02\")\n\nMrcOutputs\x12\x1b\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\n.MrcOutput2/\n\x03MRC\x12(\n\x0cSendQuestion\x12\t.MrcInput\x1a\x0b.MrcOutputs\"\x00\x62\x06proto3')
)




_MRCPASSAGE = _descriptor.Descriptor(
  name='MrcPassage',
  full_name='MrcPassage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='original', full_name='MrcPassage.original', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='morp', full_name='MrcPassage.morp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='words', full_name='MrcPassage.words', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=78,
)


_MRCINPUT = _descriptor.Descriptor(
  name='MrcInput',
  full_name='MrcInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='MrcInput.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passages', full_name='MrcInput.passages', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=139,
)


_MRCOUTPUT = _descriptor.Descriptor(
  name='MrcOutput',
  full_name='MrcOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='MrcOutput.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prob', full_name='MrcOutput.prob', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=182,
)


_MRCOUTPUTS = _descriptor.Descriptor(
  name='MrcOutputs',
  full_name='MrcOutputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answers', full_name='MrcOutputs.answers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=225,
)

_MRCINPUT.fields_by_name['passages'].message_type = _MRCPASSAGE
_MRCOUTPUTS.fields_by_name['answers'].message_type = _MRCOUTPUT
DESCRIPTOR.message_types_by_name['MrcPassage'] = _MRCPASSAGE
DESCRIPTOR.message_types_by_name['MrcInput'] = _MRCINPUT
DESCRIPTOR.message_types_by_name['MrcOutput'] = _MRCOUTPUT
DESCRIPTOR.message_types_by_name['MrcOutputs'] = _MRCOUTPUTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MrcPassage = _reflection.GeneratedProtocolMessageType('MrcPassage', (_message.Message,), dict(
  DESCRIPTOR = _MRCPASSAGE,
  __module__ = 'minds_mrc_pb2'
  # @@protoc_insertion_point(class_scope:MrcPassage)
  ))
_sym_db.RegisterMessage(MrcPassage)

MrcInput = _reflection.GeneratedProtocolMessageType('MrcInput', (_message.Message,), dict(
  DESCRIPTOR = _MRCINPUT,
  __module__ = 'minds_mrc_pb2'
  # @@protoc_insertion_point(class_scope:MrcInput)
  ))
_sym_db.RegisterMessage(MrcInput)

MrcOutput = _reflection.GeneratedProtocolMessageType('MrcOutput', (_message.Message,), dict(
  DESCRIPTOR = _MRCOUTPUT,
  __module__ = 'minds_mrc_pb2'
  # @@protoc_insertion_point(class_scope:MrcOutput)
  ))
_sym_db.RegisterMessage(MrcOutput)

MrcOutputs = _reflection.GeneratedProtocolMessageType('MrcOutputs', (_message.Message,), dict(
  DESCRIPTOR = _MRCOUTPUTS,
  __module__ = 'minds_mrc_pb2'
  # @@protoc_insertion_point(class_scope:MrcOutputs)
  ))
_sym_db.RegisterMessage(MrcOutputs)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class MRCStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SendQuestion = channel.unary_unary(
          '/MRC/SendQuestion',
          request_serializer=MrcInput.SerializeToString,
          response_deserializer=MrcOutputs.FromString,
          )


  class MRCServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def SendQuestion(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_MRCServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SendQuestion': grpc.unary_unary_rpc_method_handler(
            servicer.SendQuestion,
            request_deserializer=MrcInput.FromString,
            response_serializer=MrcOutputs.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'MRC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaMRCServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SendQuestion(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaMRCStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SendQuestion(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SendQuestion.future = None


  def beta_create_MRC_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('MRC', 'SendQuestion'): MrcInput.FromString,
    }
    response_serializers = {
      ('MRC', 'SendQuestion'): MrcOutputs.SerializeToString,
    }
    method_implementations = {
      ('MRC', 'SendQuestion'): face_utilities.unary_unary_inline(servicer.SendQuestion),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_MRC_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('MRC', 'SendQuestion'): MrcInput.SerializeToString,
    }
    response_deserializers = {
      ('MRC', 'SendQuestion'): MrcOutputs.FromString,
    }
    cardinalities = {
      'SendQuestion': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'MRC', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
