# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minds/qa/ad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minds/qa/ad.proto',
  package='minds.qa',
  syntax='proto3',
  serialized_pb=_b('\n\x11minds/qa/ad.proto\x12\x08minds.qa\"(\n\x18\x44\x65\x64uctionAnswerInputText\x12\x0c\n\x04text\x18\x01 \x01(\t\"/\n\x1d\x44\x65\x64uctionAnswerResultDocument\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')
)




_DEDUCTIONANSWERINPUTTEXT = _descriptor.Descriptor(
  name='DeductionAnswerInputText',
  full_name='minds.qa.DeductionAnswerInputText',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='minds.qa.DeductionAnswerInputText.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=71,
)


_DEDUCTIONANSWERRESULTDOCUMENT = _descriptor.Descriptor(
  name='DeductionAnswerResultDocument',
  full_name='minds.qa.DeductionAnswerResultDocument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='minds.qa.DeductionAnswerResultDocument.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['DeductionAnswerInputText'] = _DEDUCTIONANSWERINPUTTEXT
DESCRIPTOR.message_types_by_name['DeductionAnswerResultDocument'] = _DEDUCTIONANSWERRESULTDOCUMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeductionAnswerInputText = _reflection.GeneratedProtocolMessageType('DeductionAnswerInputText', (_message.Message,), dict(
  DESCRIPTOR = _DEDUCTIONANSWERINPUTTEXT,
  __module__ = 'minds.qa.ad_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.DeductionAnswerInputText)
  ))
_sym_db.RegisterMessage(DeductionAnswerInputText)

DeductionAnswerResultDocument = _reflection.GeneratedProtocolMessageType('DeductionAnswerResultDocument', (_message.Message,), dict(
  DESCRIPTOR = _DEDUCTIONANSWERRESULTDOCUMENT,
  __module__ = 'minds.qa.ad_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.DeductionAnswerResultDocument)
  ))
_sym_db.RegisterMessage(DeductionAnswerResultDocument)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
