# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minds/qa/ps.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minds/qa/ps.proto',
  package='minds.qa',
  syntax='proto3',
  serialized_pb=_b('\n\x11minds/qa/ps.proto\x12\x08minds.qa\"<\n\x12PassageSearchInput\x12\x10\n\x08provider\x18\x01 \x01(\t\x12\x14\n\x0c\x64ocumentInfo\x18\x02 \x01(\t\"%\n\x13PassageSearchResult\x12\x0e\n\x06result\x18\x01 \x01(\tb\x06proto3')
)




_PASSAGESEARCHINPUT = _descriptor.Descriptor(
  name='PassageSearchInput',
  full_name='minds.qa.PassageSearchInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='provider', full_name='minds.qa.PassageSearchInput.provider', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='documentInfo', full_name='minds.qa.PassageSearchInput.documentInfo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=91,
)


_PASSAGESEARCHRESULT = _descriptor.Descriptor(
  name='PassageSearchResult',
  full_name='minds.qa.PassageSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='minds.qa.PassageSearchResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=130,
)

DESCRIPTOR.message_types_by_name['PassageSearchInput'] = _PASSAGESEARCHINPUT
DESCRIPTOR.message_types_by_name['PassageSearchResult'] = _PASSAGESEARCHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PassageSearchInput = _reflection.GeneratedProtocolMessageType('PassageSearchInput', (_message.Message,), dict(
  DESCRIPTOR = _PASSAGESEARCHINPUT,
  __module__ = 'minds.qa.ps_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.PassageSearchInput)
  ))
_sym_db.RegisterMessage(PassageSearchInput)

PassageSearchResult = _reflection.GeneratedProtocolMessageType('PassageSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _PASSAGESEARCHRESULT,
  __module__ = 'minds.qa.ps_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.PassageSearchResult)
  ))
_sym_db.RegisterMessage(PassageSearchResult)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
