# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minds/qa/semanticSearch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='minds/qa/semanticSearch.proto',
  package='minds.qa',
  syntax='proto3',
  serialized_pb=_b('\n\x1dminds/qa/semanticSearch.proto\x12\x08minds.qa\"N\n\x13SemanticSearchInput\x12\x11\n\tthresHold\x18\n \x01(\x02\x12\x12\n\nwindowSize\x18\x14 \x01(\x05\x12\x10\n\x08kbResult\x18\x1e \x01(\t\"O\n\x14SemanticSearchOutput\x12\x37\n\x0fsemanticResults\x18\n \x03(\x0b\x32\x1e.minds.qa.SemanticSearchResult\"\x83\x01\n\x14SemanticSearchResult\x12\x13\n\x0bpassageText\x18\n \x01(\t\x12\x13\n\x0bpassageMorp\x18\x14 \x03(\t\x12\x0e\n\x06weight\x18\x1e \x01(\x02\x12\x0f\n\x07\x64ocType\x18( \x01(\t\x12\x0c\n\x04rank\x18\x32 \x01(\x05\x12\x12\n\ncreateDate\x18< \x01(\x03\x32\x80\x02\n\x15SemanticSearchService\x12K\n\nSearchBM25\x12\x1d.minds.qa.SemanticSearchInput\x1a\x1e.minds.qa.SemanticSearchOutput\x12J\n\tSearchTIC\x12\x1d.minds.qa.SemanticSearchInput\x1a\x1e.minds.qa.SemanticSearchOutput\x12N\n\rSearchBoolean\x12\x1d.minds.qa.SemanticSearchInput\x1a\x1e.minds.qa.SemanticSearchOutputb\x06proto3')
)




_SEMANTICSEARCHINPUT = _descriptor.Descriptor(
  name='SemanticSearchInput',
  full_name='minds.qa.SemanticSearchInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='thresHold', full_name='minds.qa.SemanticSearchInput.thresHold', index=0,
      number=10, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='windowSize', full_name='minds.qa.SemanticSearchInput.windowSize', index=1,
      number=20, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kbResult', full_name='minds.qa.SemanticSearchInput.kbResult', index=2,
      number=30, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=121,
)


_SEMANTICSEARCHOUTPUT = _descriptor.Descriptor(
  name='SemanticSearchOutput',
  full_name='minds.qa.SemanticSearchOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='semanticResults', full_name='minds.qa.SemanticSearchOutput.semanticResults', index=0,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=202,
)


_SEMANTICSEARCHRESULT = _descriptor.Descriptor(
  name='SemanticSearchResult',
  full_name='minds.qa.SemanticSearchResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='passageText', full_name='minds.qa.SemanticSearchResult.passageText', index=0,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='passageMorp', full_name='minds.qa.SemanticSearchResult.passageMorp', index=1,
      number=20, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weight', full_name='minds.qa.SemanticSearchResult.weight', index=2,
      number=30, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='docType', full_name='minds.qa.SemanticSearchResult.docType', index=3,
      number=40, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rank', full_name='minds.qa.SemanticSearchResult.rank', index=4,
      number=50, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='createDate', full_name='minds.qa.SemanticSearchResult.createDate', index=5,
      number=60, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=336,
)

_SEMANTICSEARCHOUTPUT.fields_by_name['semanticResults'].message_type = _SEMANTICSEARCHRESULT
DESCRIPTOR.message_types_by_name['SemanticSearchInput'] = _SEMANTICSEARCHINPUT
DESCRIPTOR.message_types_by_name['SemanticSearchOutput'] = _SEMANTICSEARCHOUTPUT
DESCRIPTOR.message_types_by_name['SemanticSearchResult'] = _SEMANTICSEARCHRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SemanticSearchInput = _reflection.GeneratedProtocolMessageType('SemanticSearchInput', (_message.Message,), dict(
  DESCRIPTOR = _SEMANTICSEARCHINPUT,
  __module__ = 'minds.qa.semanticSearch_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.SemanticSearchInput)
  ))
_sym_db.RegisterMessage(SemanticSearchInput)

SemanticSearchOutput = _reflection.GeneratedProtocolMessageType('SemanticSearchOutput', (_message.Message,), dict(
  DESCRIPTOR = _SEMANTICSEARCHOUTPUT,
  __module__ = 'minds.qa.semanticSearch_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.SemanticSearchOutput)
  ))
_sym_db.RegisterMessage(SemanticSearchOutput)

SemanticSearchResult = _reflection.GeneratedProtocolMessageType('SemanticSearchResult', (_message.Message,), dict(
  DESCRIPTOR = _SEMANTICSEARCHRESULT,
  __module__ = 'minds.qa.semanticSearch_pb2'
  # @@protoc_insertion_point(class_scope:minds.qa.SemanticSearchResult)
  ))
_sym_db.RegisterMessage(SemanticSearchResult)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class SemanticSearchServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.SearchBM25 = channel.unary_unary(
          '/minds.qa.SemanticSearchService/SearchBM25',
          request_serializer=SemanticSearchInput.SerializeToString,
          response_deserializer=SemanticSearchOutput.FromString,
          )
      self.SearchTIC = channel.unary_unary(
          '/minds.qa.SemanticSearchService/SearchTIC',
          request_serializer=SemanticSearchInput.SerializeToString,
          response_deserializer=SemanticSearchOutput.FromString,
          )
      self.SearchBoolean = channel.unary_unary(
          '/minds.qa.SemanticSearchService/SearchBoolean',
          request_serializer=SemanticSearchInput.SerializeToString,
          response_deserializer=SemanticSearchOutput.FromString,
          )


  class SemanticSearchServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def SearchBM25(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SearchTIC(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def SearchBoolean(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_SemanticSearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'SearchBM25': grpc.unary_unary_rpc_method_handler(
            servicer.SearchBM25,
            request_deserializer=SemanticSearchInput.FromString,
            response_serializer=SemanticSearchOutput.SerializeToString,
        ),
        'SearchTIC': grpc.unary_unary_rpc_method_handler(
            servicer.SearchTIC,
            request_deserializer=SemanticSearchInput.FromString,
            response_serializer=SemanticSearchOutput.SerializeToString,
        ),
        'SearchBoolean': grpc.unary_unary_rpc_method_handler(
            servicer.SearchBoolean,
            request_deserializer=SemanticSearchInput.FromString,
            response_serializer=SemanticSearchOutput.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'minds.qa.SemanticSearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaSemanticSearchServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SearchBM25(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SearchTIC(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def SearchBoolean(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaSemanticSearchServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def SearchBM25(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SearchBM25.future = None
    def SearchTIC(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SearchTIC.future = None
    def SearchBoolean(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    SearchBoolean.future = None


  def beta_create_SemanticSearchService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('minds.qa.SemanticSearchService', 'SearchBM25'): SemanticSearchInput.FromString,
      ('minds.qa.SemanticSearchService', 'SearchBoolean'): SemanticSearchInput.FromString,
      ('minds.qa.SemanticSearchService', 'SearchTIC'): SemanticSearchInput.FromString,
    }
    response_serializers = {
      ('minds.qa.SemanticSearchService', 'SearchBM25'): SemanticSearchOutput.SerializeToString,
      ('minds.qa.SemanticSearchService', 'SearchBoolean'): SemanticSearchOutput.SerializeToString,
      ('minds.qa.SemanticSearchService', 'SearchTIC'): SemanticSearchOutput.SerializeToString,
    }
    method_implementations = {
      ('minds.qa.SemanticSearchService', 'SearchBM25'): face_utilities.unary_unary_inline(servicer.SearchBM25),
      ('minds.qa.SemanticSearchService', 'SearchBoolean'): face_utilities.unary_unary_inline(servicer.SearchBoolean),
      ('minds.qa.SemanticSearchService', 'SearchTIC'): face_utilities.unary_unary_inline(servicer.SearchTIC),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_SemanticSearchService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('minds.qa.SemanticSearchService', 'SearchBM25'): SemanticSearchInput.SerializeToString,
      ('minds.qa.SemanticSearchService', 'SearchBoolean'): SemanticSearchInput.SerializeToString,
      ('minds.qa.SemanticSearchService', 'SearchTIC'): SemanticSearchInput.SerializeToString,
    }
    response_deserializers = {
      ('minds.qa.SemanticSearchService', 'SearchBM25'): SemanticSearchOutput.FromString,
      ('minds.qa.SemanticSearchService', 'SearchBoolean'): SemanticSearchOutput.FromString,
      ('minds.qa.SemanticSearchService', 'SearchTIC'): SemanticSearchOutput.FromString,
    }
    cardinalities = {
      'SearchBM25': cardinality.Cardinality.UNARY_UNARY,
      'SearchBoolean': cardinality.Cardinality.UNARY_UNARY,
      'SearchTIC': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'minds.qa.SemanticSearchService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
